vim.cmd([[ set autoread ]])
vim.cmd([[ set backspace=indent,eol,start ]])
vim.cmd([[ set clipboard=unnamed,unnamedplus ]])
vim.cmd([[ set encoding=utf8 ]])
vim.cmd([[ set fileencoding=utf-8 ]])
vim.cmd([[ set fileencodings=utf-8 ]])
vim.cmd([[ set fileformats=unix,dos,mac ]])
vim.cmd([[ set hidden ]])
vim.cmd([[ set nowrap ]])
vim.cmd([[ set number ]])
vim.cmd([[ set showcmd ]])
vim.cmd([[ set cmdheight=2 ]])
vim.cmd([[ set wildmenu wildmode=longest:full,full ]])
vim.cmd([[ filetype plugin indent on ]])
vim.cmd([[ set listchars=eol:¶,trail:•,tab:▸\ ]])
vim.cmd([[ set scrolloff=999 ]])
vim.cmd([[ set showmatch ]])
vim.cmd([[ set cursorline ]])
vim.cmd([[ set splitbelow ]])
vim.cmd([[ set linebreak ]])
vim.cmd([[ set showbreak=↪ ]])
vim.cmd([[ set so=10 ]])
vim.cmd([[ syntax on ]])
vim.cmd([[ set autoindent expandtab ]])
vim.cmd([[ set shiftwidth=2 softtabstop=2 tabstop=2 ]])
vim.cmd([[ set hlsearch ignorecase incsearch smartcase ]])
vim.cmd([[ set nobackup noswapfile nowritebackup ]])
vim.cmd([[ set lazyredraw ]])
vim.cmd([[ set ttyfast ]])
vim.cmd([[ let mapleader=',' ]])
vim.cmd([[ nnoremap <CR> :noh<CR><CR> ]])
vim.cmd([[ nnoremap <leader>pv :Ex<CR> ]])
vim.cmd([[ nmap <leader>l :set list!<cr> ]])
vim.cmd([[ set bg=dark ]])
vim.cmd([[ set termguicolors ]])
vim.cmd([[ colorscheme onedark ]])
vim.cmd([[ let extension = expand('%:e') ]])
